server:
  port: 8081
  servlet:
    context-path: /boy
person:
  last-name: 小高
  age: 20
  boss: true
  birth: 2019/06/15
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhouliu
  dog:
    name: 旺财
    age: 3